#!/usr/bin/env bash

unset RANK LOCAL_RANK WORLD_SIZE MASTER_ADDR MASTER_PORT
export MASTER_ADDR=127.0.0.1
export MASTER_PORT=29501

# Environment
export CUDA_VISIBLE_DEVICES=0
export TOKENIZERS_PARALLELISM=false

# ---- Paths ----
ROOT_DIR="${DATA_DIR}/outputs_sft_aya_qwen3_1.7b_danish/attribution"
TARGET='da'

BASE_CFGS=(
  "configs/sft/exp_attribution_danish_multitask.yaml"
)

# ---- Folder names under ${ROOT_DIR} ----
# NOTE: Fill in the exact subfolder names (each should contain a scores.json)
# These are generated by attribution runs with timestamps, e.g., "kmm_l1_da_2026-01-06_18-02-12"
FOLDERS=(
  "<your_attribution_run_folder>"
)


# ---- k values ----
K_VALUES="5 10 15 20 25"

# ---- Build full paths ----
DIRS=()
for folder in "${FOLDERS[@]}"; do
  DIRS+=("${ROOT_DIR}/${folder}")
done

# ---- Loop over yamls ----
for BASE_CFG in "${BASE_CFGS[@]}"; do
  echo "Running with base config: ${BASE_CFG}"

  python attribution/run_from_scores.py \
    --base-cfg "${BASE_CFG}" \
    --dirs "${DIRS[@]}" \
    -k ${K_VALUES} \
    --target "${TARGET}"
    # --eval-mode lmeval
    # --force
done
