
set -e

export NCCL_SOCKET_IFNAME=${NCCL_SOCKET_IFNAME:-eno1}
export NCCL_IB_DISABLE=1
export NCCL_SHM_DISABLE=1
export NCCL_P2P_DISABLE=1
export NCCL_ASYNC_ERROR_HANDLING=1
export NCCL_DEBUG=INFO

unset WORLD_SIZE
unset RANK
unset LOCAL_RANK

# ---- Paths ----
ROOT_DIR="${DATA_DIR}/outputs_qwen2.5_1.5b_instruct_multilingual_grpo_th/attribution"
BASE_CFG='configs/grpo/exp_qwen2.5_1.5b_instruct_big_math_gsm8k_th.yaml'
TARGET='th'

# ---- Folder names under ${ROOT_DIR} ----
# NOTE: Fill in the exact subfolder names (each should contain a scores.json)
# These are generated by attribution runs with timestamps, e.g., "kmm_l1_th_2026-01-12_13-13-51"
FOLDERS=(
  "<your_attribution_run_folder>"
)

# ---- k values ----
K_VALUES="1 2 3 4 5"

# ---- Build full paths ----
DIRS=()
for folder in "${FOLDERS[@]}"; do
  DIRS+=("${ROOT_DIR}/${folder}")
done

# ---- Run ----
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 TOKENIZERS_PARALLELISM=false accelerate launch --num_processes=6 --num_machines=1 --mixed_precision=bf16 --dynamo_backend=no \
  attribution/run_from_scores.py \
  --base-cfg "${BASE_CFG}" \
  --dirs "${DIRS[@]}" \
  -k ${K_VALUES} \
  --target "${TARGET}" \
  --eval-mode lmeval